# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys,res


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(774, 741)
        LoginWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        LoginWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 751, 721))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_login = QtWidgets.QWidget()
        self.page_login.setObjectName("page_login")
        self.widget = QtWidgets.QWidget(self.page_login)
        self.widget.setGeometry(QtCore.QRect(-10, 40, 761, 641))
        self.widget.setStyleSheet("QPushButton#pushButton, #pushButton_2, #pushButton_3, #pushButton_4, #pushButton_5{\n"
"background-color: rgba(0,0,0,0);\n"
"color: rgb(195, 7, 63);\n"
"}")
        self.widget.setObjectName("widget")
        self.label_left_bg = QtWidgets.QLabel(self.widget)
        self.label_left_bg.setGeometry(QtCore.QRect(20, 30, 331, 581))
        self.label_left_bg.setStyleSheet("border-image:url(:/pictures/pictures/test2.png);\n"
"border-top-left-radius: 50px;")
        self.label_left_bg.setText("")
        self.label_left_bg.setObjectName("label_left_bg")
        self.label_right_bg = QtWidgets.QLabel(self.widget)
        self.label_right_bg.setGeometry(QtCore.QRect(350, 30, 381, 581))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_right_bg.setFont(font)
        self.label_right_bg.setStyleSheet("background-image:url(:/pictures/pictures/rightBG2.png);\n"
"border-bottom-right-radius: 50px;")
        self.label_right_bg.setText("")
        self.label_right_bg.setObjectName("label_right_bg")
        self.login_label = QtWidgets.QLabel(self.widget)
        self.login_label.setGeometry(QtCore.QRect(440, 110, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.login_label.setFont(font)
        self.login_label.setStyleSheet("color: rgb(195, 7, 63);")
        self.login_label.setObjectName("login_label")
        self.username_input = QtWidgets.QLineEdit(self.widget)
        self.username_input.setGeometry(QtCore.QRect(440, 200, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.username_input.setFont(font)
        self.username_input.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(195,7,63);\n"
"color:rgb(255,255,255);")
        self.username_input.setObjectName("username_input")
        self.password_input = QtWidgets.QLineEdit(self.widget)
        self.password_input.setGeometry(QtCore.QRect(440, 290, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password_input.setFont(font)
        self.password_input.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(195,7,63);\n"
"color:rgb(255,255,255);")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.login_btn = QtWidgets.QPushButton(self.widget)
        self.login_btn.setGeometry(QtCore.QRect(440, 410, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.login_btn.setFont(font)
        self.login_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_btn.setStyleSheet("QPushButton{\n"
"  background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(211, 211, 211, 255), stop:1 rgba(229, 9, 20, 255));\n"
"  color: rgba(211, 211, 211, 255);\n"
"  border-radius:14px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(68, 176, 158, 255), stop:1 rgba(26, 26, 29, 255));\n"
"color: rgba(68, 176, 158, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  background-color: rgba(68, 176, 158, 255);\n"
"}")
        self.login_btn.setObjectName("login_btn")
        self.forget_label = QtWidgets.QLabel(self.widget)
        self.forget_label.setGeometry(QtCore.QRect(450, 480, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.forget_label.setFont(font)
        self.forget_label.setStyleSheet("QLabel{\n"
"color:rgb(0, 170, 255);\n"
"}\n"
"QLabel:hover{\n"
"color:rgb(0, 85, 255);\n"
"}")
        self.forget_label.setObjectName("forget_label")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(440, 510, 221, 61))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.discord_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.discord_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.discord_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(24)
        self.discord_btn.setFont(font)
        self.discord_btn.setStyleSheet("QPushButton:hover{\n"
"color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 166, 255, 255));\n"
"}\n"
"QPushButton{\n"
"background-color: rgba(0,0,0,0);\n"
"color:rgb(173, 173, 173);\n"
"}")
        self.discord_btn.setObjectName("discord_btn")
        self.horizontalLayout_2.addWidget(self.discord_btn)
        self.instagram_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.instagram_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.instagram_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(24)
        self.instagram_btn.setFont(font)
        self.instagram_btn.setStyleSheet("QPushButton:hover{\n"
"color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 166, 255, 255));\n"
"}\n"
"QPushButton{\n"
"color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(131, 58, 180, 255), stop:1 rgba(255, 220, 128, 255));\n"
"background-color: rgba(0,0,0,0);\n"
"}")
        self.instagram_btn.setObjectName("instagram_btn")
        self.horizontalLayout_2.addWidget(self.instagram_btn)
        self.skype_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.skype_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.skype_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(24)
        self.skype_btn.setFont(font)
        self.skype_btn.setStyleSheet("QPushButton:hover{\n"
"color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 166, 255, 255));\n"
"}\n"
"QPushButton{\n"
"color:rgb(85, 170, 255);\n"
"background-color: rgba(0,0,0,0);\n"
"}")
        self.skype_btn.setObjectName("skype_btn")
        self.horizontalLayout_2.addWidget(self.skype_btn)
        self.twitter_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.twitter_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.twitter_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(24)
        self.twitter_btn.setFont(font)
        self.twitter_btn.setStyleSheet("QPushButton:hover{\n"
"color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 166, 255, 255));\n"
"}\n"
"QPushButton{\n"
"color:rgb(85, 170, 255);\n"
"background-color: rgba(0,0,0,0);\n"
"}")
        self.twitter_btn.setObjectName("twitter_btn")
        self.horizontalLayout_2.addWidget(self.twitter_btn)
        self.register_btn = QtWidgets.QPushButton(self.widget)
        self.register_btn.setGeometry(QtCore.QRect(440, 370, 76, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.register_btn.setFont(font)
        self.register_btn.setStyleSheet("QPushButton:hover{\n"
"color: rgba(68, 176, 158, 255);\n"
"}\n"
"QPushButton{\n"
"background-color: rgba(0,0,0,0);\n"
"color: rgb(195, 7, 63);\n"
"}")
        self.register_btn.setObjectName("register_btn")
        self.exit_btn = QtWidgets.QPushButton(self.widget)
        self.exit_btn.setGeometry(QtCore.QRect(680, 40, 41, 41))
        self.exit_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.exit_btn.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(195, 7, 63);\n"
"border:none;\n"
"border-radius: 20px;\n"
"}")
        self.exit_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pictures/pictures/icon_close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn.setIcon(icon)
        self.exit_btn.setIconSize(QtCore.QSize(50, 50))
        self.exit_btn.setObjectName("exit_btn")
        self.stackedWidget.addWidget(self.page_login)
        self.page_signin = QtWidgets.QWidget()
        self.page_signin.setObjectName("page_signin")
        self.widget_2 = QtWidgets.QWidget(self.page_signin)
        self.widget_2.setGeometry(QtCore.QRect(-10, 40, 761, 641))
        self.widget_2.setStyleSheet("QPushButton#pushButton, #pushButton_2, #pushButton_3, #pushButton_4, #pushButton_5{\n"
"background-color: rgba(0,0,0,0);\n"
"color: rgb(195, 7, 63);\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.label_left_bg_2 = QtWidgets.QLabel(self.widget_2)
        self.label_left_bg_2.setGeometry(QtCore.QRect(20, 30, 381, 581))
        self.label_left_bg_2.setStyleSheet("border-image:url(:/pictures/pictures/signLeftBG.png);\n"
"border-top-left-radius: 50px;")
        self.label_left_bg_2.setText("")
        self.label_left_bg_2.setObjectName("label_left_bg_2")
        self.label_right_bg_2 = QtWidgets.QLabel(self.widget_2)
        self.label_right_bg_2.setGeometry(QtCore.QRect(400, 30, 331, 581))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_right_bg_2.setFont(font)
        self.label_right_bg_2.setStyleSheet("background-image: url(:/pictures/pictures/signRightBG.png);\n"
"border-bottom-right-radius: 50px;")
        self.label_right_bg_2.setText("")
        self.label_right_bg_2.setObjectName("label_right_bg_2")
        self.signup_label = QtWidgets.QLabel(self.widget_2)
        self.signup_label.setGeometry(QtCore.QRect(60, 110, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.signup_label.setFont(font)
        self.signup_label.setStyleSheet("color: rgb(195, 7, 63);")
        self.signup_label.setObjectName("signup_label")
        self.username_input_2 = QtWidgets.QLineEdit(self.widget_2)
        self.username_input_2.setGeometry(QtCore.QRect(60, 200, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.username_input_2.setFont(font)
        self.username_input_2.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(195,7,63);\n"
"color:rgb(255,255,255);")
        self.username_input_2.setObjectName("username_input_2")
        self.password_input_2 = QtWidgets.QLineEdit(self.widget_2)
        self.password_input_2.setGeometry(QtCore.QRect(60, 280, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password_input_2.setFont(font)
        self.password_input_2.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(195,7,63);\n"
"color:rgb(255,255,255);")
        self.password_input_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input_2.setObjectName("password_input_2")
        self.signup_btn = QtWidgets.QPushButton(self.widget_2)
        self.signup_btn.setGeometry(QtCore.QRect(60, 440, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.signup_btn.setFont(font)
        self.signup_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signup_btn.setStyleSheet("QPushButton{\n"
"  background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(229, 9, 20, 255), stop:1 rgba(211,211, 211, 255));\n"
"  color: rgba(211, 211, 211, 255);\n"
"  border-radius:14px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(26, 26, 29, 255), stop:1 rgba(68, 176, 158, 255) );\n"
"color: rgba(68, 176, 158, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  background-color: rgba(68, 176, 158, 255);\n"
"}")
        self.signup_btn.setObjectName("signup_btn")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.widget_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(60, 510, 221, 61))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.discord_btn_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.discord_btn_2.setMinimumSize(QtCore.QSize(50, 50))
        self.discord_btn_2.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(24)
        self.discord_btn_2.setFont(font)
        self.discord_btn_2.setStyleSheet("QPushButton:hover{\n"
"color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 166, 255, 255));\n"
"}\n"
"QPushButton{\n"
"background-color: rgba(0,0,0,0);\n"
"color:rgb(173, 173, 173);\n"
"}")
        self.discord_btn_2.setObjectName("discord_btn_2")
        self.horizontalLayout_3.addWidget(self.discord_btn_2)
        self.instagram_btn_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.instagram_btn_2.setMinimumSize(QtCore.QSize(50, 50))
        self.instagram_btn_2.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(24)
        self.instagram_btn_2.setFont(font)
        self.instagram_btn_2.setStyleSheet("QPushButton:hover{\n"
"color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 166, 255, 255));\n"
"}\n"
"QPushButton{\n"
"color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(131, 58, 180, 255), stop:1 rgba(255, 220, 128, 255));\n"
"background-color: rgba(0,0,0,0);\n"
"}")
        self.instagram_btn_2.setObjectName("instagram_btn_2")
        self.horizontalLayout_3.addWidget(self.instagram_btn_2)
        self.skype_btn_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.skype_btn_2.setMinimumSize(QtCore.QSize(50, 50))
        self.skype_btn_2.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(24)
        self.skype_btn_2.setFont(font)
        self.skype_btn_2.setStyleSheet("QPushButton:hover{\n"
"color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 166, 255, 255));\n"
"}\n"
"QPushButton{\n"
"color:rgb(85, 170, 255);\n"
"background-color: rgba(0,0,0,0);\n"
"}")
        self.skype_btn_2.setObjectName("skype_btn_2")
        self.horizontalLayout_3.addWidget(self.skype_btn_2)
        self.twitter_btn_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.twitter_btn_2.setMinimumSize(QtCore.QSize(50, 50))
        self.twitter_btn_2.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(24)
        self.twitter_btn_2.setFont(font)
        self.twitter_btn_2.setStyleSheet("QPushButton:hover{\n"
"color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 166, 255, 255));\n"
"}\n"
"QPushButton{\n"
"color:rgb(85, 170, 255);\n"
"background-color: rgba(0,0,0,0);\n"
"}")
        self.twitter_btn_2.setObjectName("twitter_btn_2")
        self.horizontalLayout_3.addWidget(self.twitter_btn_2)
        self.confirmpass_input = QtWidgets.QLineEdit(self.widget_2)
        self.confirmpass_input.setGeometry(QtCore.QRect(60, 360, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.confirmpass_input.setFont(font)
        self.confirmpass_input.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(195,7,63);\n"
"color:rgb(255,255,255);")
        self.confirmpass_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmpass_input.setObjectName("confirmpass_input")
        self.exit_btn_2 = QtWidgets.QPushButton(self.widget_2)
        self.exit_btn_2.setGeometry(QtCore.QRect(680, 40, 41, 41))
        self.exit_btn_2.setMinimumSize(QtCore.QSize(0, 0))
        self.exit_btn_2.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.exit_btn_2.setFont(font)
        self.exit_btn_2.setStyleSheet("QPushButton{\n"
"background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(195, 7, 63);\n"
"border:none;\n"
"border-radius: 20px;\n"
"}")
        self.exit_btn_2.setText("")
        self.exit_btn_2.setIcon(icon)
        self.exit_btn_2.setIconSize(QtCore.QSize(50, 50))
        self.exit_btn_2.setObjectName("exit_btn_2")
        self.stackedWidget.addWidget(self.page_signin)
        LoginWindow.setCentralWidget(self.centralwidget)

        self.widget.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0))
        self.login_btn.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0))

        self.retranslateUi(LoginWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.login_label.setText(_translate("LoginWindow", "Log In"))
        self.username_input.setPlaceholderText(_translate("LoginWindow", "Username"))
        self.password_input.setPlaceholderText(_translate("LoginWindow", "Password"))
        self.login_btn.setText(_translate("LoginWindow", "E n t e r"))
        self.login_btn.setShortcut(_translate("LoginWindow", "Return"))
        self.forget_label.setText(_translate("LoginWindow", "Забыли логин или пароль?"))
        self.discord_btn.setText(_translate("LoginWindow", "Y"))
        self.instagram_btn.setText(_translate("LoginWindow", "Q"))
        self.skype_btn.setText(_translate("LoginWindow", "I"))
        self.twitter_btn.setText(_translate("LoginWindow", "D"))
        self.register_btn.setText(_translate("LoginWindow", "Sign Up"))
        self.signup_label.setText(_translate("LoginWindow", "Sign Up"))
        self.username_input_2.setPlaceholderText(_translate("LoginWindow", "Username"))
        self.password_input_2.setPlaceholderText(_translate("LoginWindow", "Password"))
        self.signup_btn.setText(_translate("LoginWindow", "Register"))
        self.discord_btn_2.setText(_translate("LoginWindow", "Y"))
        self.instagram_btn_2.setText(_translate("LoginWindow", "Q"))
        self.skype_btn_2.setText(_translate("LoginWindow", "I"))
        self.twitter_btn_2.setText(_translate("LoginWindow", "D"))
        self.confirmpass_input.setPlaceholderText(_translate("LoginWindow", "Confirm password"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
