# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(892, 558)
        MainWindow.setMinimumSize(QtCore.QSize(892, 558))
        MainWindow.setMaximumSize(QtCore.QSize(892, 558))
        MainWindow.setStyleSheet("#MainWindow{\n"
"background-color: #282c34;\n"
"border-bottom:2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(170,0,0), stop:1 #21252b);\n"
"border-right: 2px solid qlineargradient(spread:pad, x1:0.469, y1:0, x2:0.475, y2:1, stop:0 rgb(170,0,0), stop:1 #21252b);\n"
"}\n"
"\n"
"#menu_btn{\n"
"padding:5px;\n"
"border:none;\n"
"width:30px;\n"
"height:30px;\n"
"}\n"
"\n"
"#header_widget{\n"
"background-color:#282c34;\n"
"border-bottom:2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #21252b, stop:1 rgb(170, 0, 0));\n"
"}\n"
"#icon_only_widget{\n"
"background-color:#282c34;\n"
"border-right:2px solid qlineargradient(spread:pad, x1:0.469, y1:0, x2:0.475, y2:1, stop:0 #21252b, stop:1 rgb(170, 0, 0));\n"
"}\n"
"\n"
"#icon_only_widget QPushButton, QLabel{\n"
"height:50px;\n"
"border:none;\n"
"}\n"
"\n"
"#icon_only_widget QPushButton:hover{\n"
"background-color: #323a4b;\n"
"}\n"
"\n"
"#icon_only_widget QPushButton:pressed{\n"
"border-left: 2px solid rgb(195,7,63);\n"
"}\n"
"\n"
"#icon_only_widget QPushButton:checked{\n"
"border-left: 2px solid rgb(195,7,63);\n"
"}\n"
"\n"
"#logo_label_1{\n"
"}\n"
"\n"
"#full_menu_widget{\n"
"background-color: #282c34;\n"
"border-right:2px solid qlineargradient(spread:pad, x1:0.469, y1:0, x2:0.475, y2:1, stop:0 #21252b, stop:1 rgb(170, 0, 0));\n"
"}\n"
"\n"
"#full_menu_widget QPushButton{\n"
"border:none;\n"
"text-allign:center;\n"
"height:33px;\n"
"padding: 8px 0px 8px 3px;\n"
"color:#fff;\n"
"}\n"
"\n"
"#full_menu_widget QPushButton:hover{\n"
"border-bottom:3px solid #323a4b;\n"
"background-color: #323a4b;\n"
"border-radius:6px;\n"
"}\n"
"\n"
"#full_menu_widget QPushButton:checked{\n"
"border-left: 2px solid rgb(195,7,63);\n"
"}\n"
"\n"
"#logo_label_2{\n"
"padding-right: 10px;\n"
"}\n"
"\n"
"#search_btn{\n"
"border:none;\n"
"}\n"
"\n"
"#search_input{\n"
"border:none;\n"
"border-radius:2px;\n"
"padding: 5px 10px;\n"
"}\n"
"\n"
"#search_input:focus{\n"
"background-color: rgba(176, 243, 241, 255);\n"
"}\n"
"\n"
"#account_btn{\n"
"border:none;\n"
"padding-right:5px;;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.header_widget = QtWidgets.QWidget(self.widget_3)
        self.header_widget.setMinimumSize(QtCore.QSize(0, 40))
        self.header_widget.setMaximumSize(QtCore.QSize(1000, 1000))
        self.header_widget.setStyleSheet("bachground-color: rgb(85, 85, 127);")
        self.header_widget.setObjectName("header_widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.header_widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.menu_btn = QtWidgets.QPushButton(self.header_widget)
        self.menu_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/arrow-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/icon_menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.menu_btn.setIcon(icon)
        self.menu_btn.setIconSize(QtCore.QSize(34, 34))
        self.menu_btn.setCheckable(True)
        self.menu_btn.setAutoExclusive(True)
        self.menu_btn.setObjectName("menu_btn")
        self.horizontalLayout_4.addWidget(self.menu_btn)
        spacerItem = QtWidgets.QSpacerItem(226, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_input = QtWidgets.QLineEdit(self.header_widget)
        self.search_input.setObjectName("search_input")
        self.horizontalLayout.addWidget(self.search_input)
        self.search_btn = QtWidgets.QPushButton(self.header_widget)
        self.search_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_btn.setIcon(icon1)
        self.search_btn.setIconSize(QtCore.QSize(20, 20))
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout.addWidget(self.search_btn)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(226, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.account_btn = QtWidgets.QPushButton(self.header_widget)
        self.account_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/account.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/account_active.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.account_btn.setIcon(icon2)
        self.account_btn.setIconSize(QtCore.QSize(18, 18))
        self.account_btn.setCheckable(True)
        self.account_btn.setAutoExclusive(False)
        self.account_btn.setObjectName("account_btn")
        self.horizontalLayout_4.addWidget(self.account_btn)
        self.verticalLayout_5.addWidget(self.header_widget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_encrypt = QtWidgets.QWidget()
        self.page_encrypt.setStyleSheet("")
        self.page_encrypt.setObjectName("page_encrypt")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_encrypt)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.page_encrypt)
        self.widget_2.setObjectName("widget_2")
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setGeometry(QtCore.QRect(0, 0, 692, 491))
        self.widget.setObjectName("widget")
        self.res_file_line = QtWidgets.QLineEdit(self.widget)
        self.res_file_line.setGeometry(QtCore.QRect(300, 290, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Moon")
        self.res_file_line.setFont(font)
        self.res_file_line.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(176, 243, 241, 255), stop:1 rgba(0, 0, 0, 255));\n"
"color:rgb(255,255,255);\n"
"border-radius:3px;")
        self.res_file_line.setAlignment(QtCore.Qt.AlignCenter)
        self.res_file_line.setReadOnly(True)
        self.res_file_line.setObjectName("res_file_line")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(190, 20, 481, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.choose_file_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.choose_file_btn.setMaximumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setBold(False)
        font.setWeight(50)
        self.choose_file_btn.setFont(font)
        self.choose_file_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(20,20,20,50);\n"
"border-bottom:2px solid rgba(195, 7, 63, 255);\n"
"border-radius:6px;\n"
"color:rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(20,20,20,100);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid rgba(176, 243, 241, 255);\n"
"background-color: rgba(20, 20, 20, 255);\n"
"border-radius:15px;\n"
"}")
        self.choose_file_btn.setObjectName("choose_file_btn")
        self.horizontalLayout_5.addWidget(self.choose_file_btn)
        self.choose_folder_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.choose_folder_btn.setMaximumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setBold(False)
        font.setWeight(50)
        self.choose_folder_btn.setFont(font)
        self.choose_folder_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(20,20,20,50);\n"
"border-bottom:2px solid rgba(195, 7, 63, 255);\n"
"border-radius:6px;\n"
"color:rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(20,20,20,100);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid rgba(176, 243, 241, 255);\n"
"background-color: rgba(20, 20, 20, 255);\n"
"border-radius:15px;\n"
"}")
        self.choose_folder_btn.setObjectName("choose_folder_btn")
        self.horizontalLayout_5.addWidget(self.choose_folder_btn)
        self.info_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.info_btn.setMaximumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setBold(False)
        font.setWeight(50)
        self.info_btn.setFont(font)
        self.info_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(20,20,20,50);\n"
"border-bottom:2px solid rgba(195, 7, 63, 255);\n"
"border-radius:6px;\n"
"color:rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(20,20,20,100);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid rgba(176, 243, 241, 255);\n"
"background-color: rgba(20, 20, 20, 255);\n"
"border-radius:15px;\n"
"}")
        self.info_btn.setObjectName("info_btn")
        self.horizontalLayout_5.addWidget(self.info_btn)
        self.encrypt_btn = QtWidgets.QPushButton(self.widget)
        self.encrypt_btn.setGeometry(QtCore.QRect(410, 390, 51, 51))
        self.encrypt_btn.setMaximumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setBold(False)
        font.setWeight(50)
        self.encrypt_btn.setFont(font)
        self.encrypt_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(20,20,20,50);\n"
"border-bottom:2px solid rgba(195, 7, 63, 255);\n"
"border-radius:6px;\n"
"color:rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(20,20,20,100);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid rgba(176, 243, 241, 255);\n"
"background-color: rgba(20, 20, 20, 255);\n"
"border-radius:15px;\n"
"}")
        self.encrypt_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/lock-locked.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.encrypt_btn.setIcon(icon3)
        self.encrypt_btn.setIconSize(QtCore.QSize(18, 18))
        self.encrypt_btn.setObjectName("encrypt_btn")
        self.label_protect = QtWidgets.QLabel(self.widget)
        self.label_protect.setGeometry(QtCore.QRect(0, -10, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(16)
        font.setUnderline(False)
        self.label_protect.setFont(font)
        self.label_protect.setStyleSheet("color: rgb(195, 7, 63);\n"
"")
        self.label_protect.setObjectName("label_protect")
        self.gridLayout_3.addWidget(self.widget_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_encrypt)
        self.page_decrypt = QtWidgets.QWidget()
        self.page_decrypt.setObjectName("page_decrypt")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_decrypt)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.page_decrypt)
        self.widget_4.setObjectName("widget_4")
        self.res_file_line_2 = QtWidgets.QLineEdit(self.widget_4)
        self.res_file_line_2.setGeometry(QtCore.QRect(300, 290, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Moon")
        self.res_file_line_2.setFont(font)
        self.res_file_line_2.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(176, 243, 241, 255), stop:1 rgba(0, 0, 0, 255));\n"
"color:rgb(255,255,255);\n"
"border-radius:3px;")
        self.res_file_line_2.setAlignment(QtCore.Qt.AlignCenter)
        self.res_file_line_2.setReadOnly(True)
        self.res_file_line_2.setObjectName("res_file_line_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.widget_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(190, 20, 481, 251))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.choose_file_btn_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.choose_file_btn_2.setMaximumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setBold(False)
        font.setWeight(50)
        self.choose_file_btn_2.setFont(font)
        self.choose_file_btn_2.setStyleSheet("QPushButton{\n"
"background-color: rgba(20,20,20,50);\n"
"border-bottom:2px solid rgba(195, 7, 63, 255);\n"
"border-radius:6px;\n"
"color:rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(20,20,20,100);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid rgba(176, 243, 241, 255);\n"
"background-color: rgba(20, 20, 20, 255);\n"
"border-radius:15px;\n"
"}")
        self.choose_file_btn_2.setObjectName("choose_file_btn_2")
        self.horizontalLayout_6.addWidget(self.choose_file_btn_2)
        self.choose_folder_btn_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.choose_folder_btn_2.setMaximumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setBold(False)
        font.setWeight(50)
        self.choose_folder_btn_2.setFont(font)
        self.choose_folder_btn_2.setStyleSheet("QPushButton{\n"
"background-color: rgba(20,20,20,50);\n"
"border-bottom:2px solid rgba(195, 7, 63, 255);\n"
"border-radius:6px;\n"
"color:rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(20,20,20,100);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid rgba(176, 243, 241, 255);\n"
"background-color: rgba(20, 20, 20, 255);\n"
"border-radius:15px;\n"
"}")
        self.choose_folder_btn_2.setObjectName("choose_folder_btn_2")
        self.horizontalLayout_6.addWidget(self.choose_folder_btn_2)
        self.decrypt_btn = QtWidgets.QPushButton(self.widget_4)
        self.decrypt_btn.setGeometry(QtCore.QRect(410, 390, 51, 51))
        self.decrypt_btn.setMaximumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setBold(False)
        font.setWeight(50)
        self.decrypt_btn.setFont(font)
        self.decrypt_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(20,20,20,50);\n"
"border-bottom:2px solid rgba(195, 7, 63, 255);\n"
"border-radius:6px;\n"
"color:rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(20,20,20,100);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid rgba(176, 243, 241, 255);\n"
"background-color: rgba(20, 20, 20, 255);\n"
"border-radius:15px;\n"
"}")
        self.decrypt_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/lock-unlocked.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.decrypt_btn.setIcon(icon4)
        self.decrypt_btn.setIconSize(QtCore.QSize(18, 18))
        self.decrypt_btn.setObjectName("decrypt_btn")
        self.label_unlock = QtWidgets.QLabel(self.widget_4)
        self.label_unlock.setGeometry(QtCore.QRect(0, 0, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_unlock.setFont(font)
        self.label_unlock.setStyleSheet("color: rgb(195,7,63);")
        self.label_unlock.setObjectName("label_unlock")
        self.gridLayout_2.addWidget(self.widget_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_decrypt)
        self.secure_plus_page = QtWidgets.QWidget()
        self.secure_plus_page.setObjectName("secure_plus_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.secure_plus_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_5 = QtWidgets.QWidget(self.secure_plus_page)
        self.widget_5.setObjectName("widget_5")
        self.label_secure_plus = QtWidgets.QLabel(self.widget_5)
        self.label_secure_plus.setGeometry(QtCore.QRect(0, -10, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_secure_plus.setFont(font)
        self.label_secure_plus.setStyleSheet("color: #FFD700;")
        self.label_secure_plus.setObjectName("label_secure_plus")
        self.res_file_line_3 = QtWidgets.QLineEdit(self.widget_5)
        self.res_file_line_3.setGeometry(QtCore.QRect(300, 290, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Moon")
        self.res_file_line_3.setFont(font)
        self.res_file_line_3.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(176, 243, 241, 255), stop:1 rgba(0, 0, 0, 255));\n"
"color: #FFD700;\n"
"border-radius:3px;")
        self.res_file_line_3.setAlignment(QtCore.Qt.AlignCenter)
        self.res_file_line_3.setReadOnly(True)
        self.res_file_line_3.setObjectName("res_file_line_3")
        self.encrypt_btn_2 = QtWidgets.QPushButton(self.widget_5)
        self.encrypt_btn_2.setGeometry(QtCore.QRect(410, 390, 51, 51))
        self.encrypt_btn_2.setMaximumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setBold(False)
        font.setWeight(50)
        self.encrypt_btn_2.setFont(font)
        self.encrypt_btn_2.setStyleSheet("QPushButton{\n"
"background-color: rgba(20,20,20,50);\n"
"border-bottom:2px solid rgba(195, 7, 63, 255);\n"
"border-radius:6px;\n"
"color:rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(20,20,20,100);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid rgba(176, 243, 241, 255);\n"
"background-color: rgba(20, 20, 20, 255);\n"
"border-radius:15px;\n"
"}")
        self.encrypt_btn_2.setText("")
        self.encrypt_btn_2.setIcon(icon3)
        self.encrypt_btn_2.setIconSize(QtCore.QSize(18, 18))
        self.encrypt_btn_2.setObjectName("encrypt_btn_2")
        self.layoutWidget_4 = QtWidgets.QWidget(self.widget_5)
        self.layoutWidget_4.setGeometry(QtCore.QRect(190, 20, 481, 251))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.choose_file_btn_3 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.choose_file_btn_3.setMaximumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setBold(False)
        font.setWeight(50)
        self.choose_file_btn_3.setFont(font)
        self.choose_file_btn_3.setStyleSheet("QPushButton{\n"
"background-color: rgba(20,20,20,50);\n"
"border-bottom:2px solid rgba(195, 7, 63, 255);\n"
"border-radius:6px;\n"
"color:rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(20,20,20,100);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid rgba(176, 243, 241, 255);\n"
"background-color: rgba(20, 20, 20, 255);\n"
"border-radius:15px;\n"
"}")
        self.choose_file_btn_3.setObjectName("choose_file_btn_3")
        self.horizontalLayout_10.addWidget(self.choose_file_btn_3)
        self.info_btn_2 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.info_btn_2.setMaximumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setBold(False)
        font.setWeight(50)
        self.info_btn_2.setFont(font)
        self.info_btn_2.setStyleSheet("QPushButton{\n"
"background-color: rgba(20,20,20,50);\n"
"border-bottom:2px solid rgba(195, 7, 63, 255);\n"
"border-radius:6px;\n"
"color:rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(20,20,20,100);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid rgba(176, 243, 241, 255);\n"
"background-color: rgba(20, 20, 20, 255);\n"
"border-radius:15px;\n"
"}")
        self.info_btn_2.setObjectName("info_btn_2")
        self.horizontalLayout_10.addWidget(self.info_btn_2)
        self.gridLayout_4.addWidget(self.widget_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.secure_plus_page)
        self.files_pages = QtWidgets.QWidget()
        self.files_pages.setObjectName("files_pages")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.files_pages)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_6 = QtWidgets.QWidget(self.files_pages)
        self.widget_6.setObjectName("widget_6")
        self.res_file_line_4 = QtWidgets.QLineEdit(self.widget_6)
        self.res_file_line_4.setGeometry(QtCore.QRect(300, 290, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Moon")
        self.res_file_line_4.setFont(font)
        self.res_file_line_4.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(176, 243, 241, 255), stop:1 rgba(0, 0, 0, 255));\n"
"color:rgb(255,255,255);\n"
"border-radius:3px;")
        self.res_file_line_4.setAlignment(QtCore.Qt.AlignCenter)
        self.res_file_line_4.setReadOnly(True)
        self.res_file_line_4.setObjectName("res_file_line_4")
        self.layoutWidget_3 = QtWidgets.QWidget(self.widget_6)
        self.layoutWidget_3.setGeometry(QtCore.QRect(190, 20, 481, 251))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.choose_file_btn_4 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.choose_file_btn_4.setMaximumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setBold(False)
        font.setWeight(50)
        self.choose_file_btn_4.setFont(font)
        self.choose_file_btn_4.setStyleSheet("QPushButton{\n"
"background-color: rgba(20,20,20,50);\n"
"border-bottom:2px solid rgba(195, 7, 63, 255);\n"
"border-radius:6px;\n"
"color:rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(20,20,20,100);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid rgba(176, 243, 241, 255);\n"
"background-color: rgba(20, 20, 20, 255);\n"
"border-radius:15px;\n"
"}")
        self.choose_file_btn_4.setObjectName("choose_file_btn_4")
        self.horizontalLayout_7.addWidget(self.choose_file_btn_4)
        self.choose_folder_btn_4 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.choose_folder_btn_4.setMaximumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setBold(False)
        font.setWeight(50)
        self.choose_folder_btn_4.setFont(font)
        self.choose_folder_btn_4.setStyleSheet("QPushButton{\n"
"background-color: rgba(20,20,20,50);\n"
"border-bottom:2px solid rgba(195, 7, 63, 255);\n"
"border-radius:6px;\n"
"color:rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(20,20,20,100);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid rgba(176, 243, 241, 255);\n"
"background-color: rgba(20, 20, 20, 255);\n"
"border-radius:15px;\n"
"}")
        self.choose_folder_btn_4.setObjectName("choose_folder_btn_4")
        self.horizontalLayout_7.addWidget(self.choose_folder_btn_4)
        self.delete_btn = QtWidgets.QPushButton(self.widget_6)
        self.delete_btn.setGeometry(QtCore.QRect(410, 390, 51, 51))
        self.delete_btn.setMaximumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setFamily("Moon")
        self.delete_btn.setFont(font)
        self.delete_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(20,20,20,50);\n"
"border-bottom:2px solid rgba(195, 7, 63, 255);\n"
"border-radius:6px;\n"
"color:rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(20,20,20,100);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid rgba(176, 243, 241, 255);\n"
"background-color: rgba(20, 20, 20, 255);\n"
"border-radius:15px;\n"
"}")
        self.delete_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/icon_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_btn.setIcon(icon5)
        self.delete_btn.setIconSize(QtCore.QSize(18, 18))
        self.delete_btn.setObjectName("delete_btn")
        self.label_filemanager = QtWidgets.QLabel(self.widget_6)
        self.label_filemanager.setGeometry(QtCore.QRect(0, -10, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(16)
        self.label_filemanager.setFont(font)
        self.label_filemanager.setStyleSheet("color: rgb(195,7,63);")
        self.label_filemanager.setObjectName("label_filemanager")
        self.gridLayout_5.addWidget(self.widget_6, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.files_pages)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setObjectName("settings_page")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.settings_page)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget_7 = QtWidgets.QWidget(self.settings_page)
        self.widget_7.setObjectName("widget_7")
        self.radioButton = QtWidgets.QRadioButton(self.widget_7)
        self.radioButton.setGeometry(QtCore.QRect(20, 40, 82, 17))
        self.radioButton.setStyleSheet("color: white;\n"
"background-color: rgba(20,20,20,50);")
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget_7)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 60, 82, 17))
        self.radioButton_2.setStyleSheet("color: white;\n"
"background-color: rgba(20,20,20,50);")
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_language = QtWidgets.QLabel(self.widget_7)
        self.label_language.setGeometry(QtCore.QRect(20, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_language.setFont(font)
        self.label_language.setStyleSheet("color: rgb(195,7,63);")
        self.label_language.setObjectName("label_language")
        self.label_lisence = QtWidgets.QLabel(self.widget_7)
        self.label_lisence.setGeometry(QtCore.QRect(20, 100, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_lisence.setFont(font)
        self.label_lisence.setStyleSheet("color: rgb(195,7,63);")
        self.label_lisence.setObjectName("label_lisence")
        self.lisence_btn = QtWidgets.QPushButton(self.widget_7)
        self.lisence_btn.setGeometry(QtCore.QRect(20, 130, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setBold(False)
        font.setWeight(50)
        self.lisence_btn.setFont(font)
        self.lisence_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(20,20,20,50);\n"
"border-bottom:2px solid rgba(195, 7, 63, 255);\n"
"border-radius:6px;\n"
"color:rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(20,20,20,100);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid rgba(176, 243, 241, 255);\n"
"background-color: rgba(20, 20, 20, 255);\n"
"border-radius:15px;\n"
"}")
        self.lisence_btn.setObjectName("lisence_btn")
        self.label_instructions = QtWidgets.QLabel(self.widget_7)
        self.label_instructions.setGeometry(QtCore.QRect(20, 180, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_instructions.setFont(font)
        self.label_instructions.setStyleSheet("color: rgb(195,7,63);")
        self.label_instructions.setObjectName("label_instructions")
        self.instruction_btn = QtWidgets.QPushButton(self.widget_7)
        self.instruction_btn.setGeometry(QtCore.QRect(20, 220, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setBold(False)
        font.setWeight(50)
        self.instruction_btn.setFont(font)
        self.instruction_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(20,20,20,50);\n"
"border-bottom:2px solid rgba(195, 7, 63, 255);\n"
"border-radius:6px;\n"
"color:rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(20,20,20,100);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid rgba(176, 243, 241, 255);\n"
"background-color: rgba(20, 20, 20, 255);\n"
"border-radius:15px;\n"
"}")
        self.instruction_btn.setObjectName("instruction_btn")
        self.label_gmail = QtWidgets.QLabel(self.widget_7)
        self.label_gmail.setGeometry(QtCore.QRect(0, 460, 141, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_gmail.setFont(font)
        self.label_gmail.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_gmail.setObjectName("label_gmail")
        self.layoutWidget1 = QtWidgets.QWidget(self.widget_7)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 480, 348, 19))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_whitepart = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_whitepart.setFont(font)
        self.label_whitepart.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_whitepart.setObjectName("label_whitepart")
        self.horizontalLayout_8.addWidget(self.label_whitepart)
        self.label_redpart = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_redpart.setFont(font)
        self.label_redpart.setStyleSheet("color: rgb(195,7,63);")
        self.label_redpart.setObjectName("label_redpart")
        self.horizontalLayout_8.addWidget(self.label_redpart)
        self.gridLayout_6.addWidget(self.widget_7, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.settings_page)
        self.user_page = QtWidgets.QWidget()
        self.user_page.setObjectName("user_page")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.user_page)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_8 = QtWidgets.QWidget(self.user_page)
        self.widget_8.setObjectName("widget_8")
        self.label_2 = QtWidgets.QLabel(self.widget_8)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_username = QtWidgets.QLabel(self.widget_8)
        self.label_username.setGeometry(QtCore.QRect(180, 30, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_username.setFont(font)
        self.label_username.setStyleSheet("QLabel{\n"
"color: rgb(195,7,63);\n"
"}\n"
"QLabel:hover{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.label_username.setObjectName("label_username")
        self.label_3 = QtWidgets.QLabel(self.widget_8)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_regdate = QtWidgets.QLabel(self.widget_8)
        self.label_regdate.setGeometry(QtCore.QRect(170, 180, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_regdate.setFont(font)
        self.label_regdate.setStyleSheet("QLabel{\n"
"color: rgb(195,7,63);\n"
"}\n"
"QLabel:hover{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.label_regdate.setObjectName("label_regdate")
        self.label_4 = QtWidgets.QLabel(self.widget_8)
        self.label_4.setGeometry(QtCore.QRect(0, 360, 581, 51))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(195, 7, 63);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget_8)
        self.label_5.setGeometry(QtCore.QRect(250, 50, 183, 20))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.logout_btn = QtWidgets.QPushButton(self.widget_8)
        self.logout_btn.setGeometry(QtCore.QRect(0, 450, 41, 51))
        self.logout_btn.setMaximumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setFamily("Moon")
        self.logout_btn.setFont(font)
        self.logout_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(20,20,20,50);\n"
"border-radius:6px;\n"
"color:rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(20,20,20,100);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid rgba(176, 243, 241, 255);\n"
"background-color: rgba(20, 20, 20, 255);\n"
"border-radius:15px;\n"
"}")
        self.logout_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/account-logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout_btn.setIcon(icon6)
        self.logout_btn.setIconSize(QtCore.QSize(18, 18))
        self.logout_btn.setObjectName("logout_btn")
        self.delete_acc_btn = QtWidgets.QPushButton(self.widget_8)
        self.delete_acc_btn.setGeometry(QtCore.QRect(0, 310, 131, 51))
        self.delete_acc_btn.setMaximumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setBold(False)
        font.setWeight(50)
        self.delete_acc_btn.setFont(font)
        self.delete_acc_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(20,20,20,50);\n"
"border-bottom:2px solid rgba(195, 7, 63, 255);\n"
"border-radius:6px;\n"
"color:rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(20,20,20,100);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid rgba(176, 243, 241, 255);\n"
"background-color: rgba(20, 20, 20, 255);\n"
"border-radius:15px;\n"
"}")
        self.delete_acc_btn.setObjectName("delete_acc_btn")
        self.gridLayout_7.addWidget(self.widget_8, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.user_page)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_3, 0, 2, 1, 1)
        self.full_menu_widget = QtWidgets.QWidget(self.centralwidget)
        self.full_menu_widget.setMaximumSize(QtCore.QSize(147, 558))
        self.full_menu_widget.setObjectName("full_menu_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.full_menu_widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logo_label_1 = QtWidgets.QLabel(self.full_menu_widget)
        self.logo_label_1.setMinimumSize(QtCore.QSize(40, 40))
        self.logo_label_1.setMaximumSize(QtCore.QSize(40, 40))
        self.logo_label_1.setText("")
        self.logo_label_1.setPixmap(QtGui.QPixmap(":/icons/icons/arch_logo.png"))
        self.logo_label_1.setScaledContents(True)
        self.logo_label_1.setObjectName("logo_label_1")
        self.horizontalLayout_2.addWidget(self.logo_label_1)
        self.logo_label_2 = QtWidgets.QLabel(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.logo_label_2.setFont(font)
        self.logo_label_2.setStyleSheet("color:#E3E2DF;")
        self.logo_label_2.setObjectName("logo_label_2")
        self.horizontalLayout_2.addWidget(self.logo_label_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.encrypt_menu_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.encrypt_menu_btn_2.setFont(font)
        self.encrypt_menu_btn_2.setStyleSheet("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/lock-locked.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/lock-locked-active.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.encrypt_menu_btn_2.setIcon(icon7)
        self.encrypt_menu_btn_2.setIconSize(QtCore.QSize(20, 20))
        self.encrypt_menu_btn_2.setCheckable(True)
        self.encrypt_menu_btn_2.setAutoExclusive(True)
        self.encrypt_menu_btn_2.setObjectName("encrypt_menu_btn_2")
        self.verticalLayout_2.addWidget(self.encrypt_menu_btn_2)
        self.decrypt_menu_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.decrypt_menu_btn_2.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/lock-unlocked.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/lock-unlocked-active.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.decrypt_menu_btn_2.setIcon(icon8)
        self.decrypt_menu_btn_2.setIconSize(QtCore.QSize(20, 20))
        self.decrypt_menu_btn_2.setCheckable(True)
        self.decrypt_menu_btn_2.setAutoExclusive(True)
        self.decrypt_menu_btn_2.setObjectName("decrypt_menu_btn_2")
        self.verticalLayout_2.addWidget(self.decrypt_menu_btn_2)
        self.key_menu_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.key_menu_btn_2.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/key.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/key_active.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.key_menu_btn_2.setIcon(icon9)
        self.key_menu_btn_2.setIconSize(QtCore.QSize(24, 24))
        self.key_menu_btn_2.setCheckable(True)
        self.key_menu_btn_2.setAutoExclusive(True)
        self.key_menu_btn_2.setObjectName("key_menu_btn_2")
        self.verticalLayout_2.addWidget(self.key_menu_btn_2)
        self.files_menu_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.files_menu_btn_2.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.files_menu_btn_2.setIcon(icon10)
        self.files_menu_btn_2.setIconSize(QtCore.QSize(20, 20))
        self.files_menu_btn_2.setCheckable(True)
        self.files_menu_btn_2.setAutoExclusive(True)
        self.files_menu_btn_2.setObjectName("files_menu_btn_2")
        self.verticalLayout_2.addWidget(self.files_menu_btn_2)
        self.settings_menu_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.settings_menu_btn_2.setFont(font)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/icon_settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/icon_settings_active.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.settings_menu_btn_2.setIcon(icon11)
        self.settings_menu_btn_2.setIconSize(QtCore.QSize(20, 20))
        self.settings_menu_btn_2.setCheckable(True)
        self.settings_menu_btn_2.setAutoExclusive(True)
        self.settings_menu_btn_2.setObjectName("settings_menu_btn_2")
        self.verticalLayout_2.addWidget(self.settings_menu_btn_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 176, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.exit_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.exit_btn_2.setFont(font)
        self.exit_btn_2.setStyleSheet("QPushButton:hover{\n"
"background-color: rgb(195,7,63);\n"
"border-bottom: 2px solid rgb(195,7,63);\n"
"}")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/icon_close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn_2.setIcon(icon12)
        self.exit_btn_2.setObjectName("exit_btn_2")
        self.verticalLayout_4.addWidget(self.exit_btn_2)
        self.gridLayout.addWidget(self.full_menu_widget, 0, 1, 1, 1)
        self.icon_only_widget = QtWidgets.QWidget(self.centralwidget)
        self.icon_only_widget.setMaximumSize(QtCore.QSize(52, 588))
        self.icon_only_widget.setStyleSheet("")
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.icon_only_widget)
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        self.label.setMaximumSize(QtCore.QSize(50, 50))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/icons/arch_logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.encrypt_menu_btn = QtWidgets.QPushButton(self.icon_only_widget)
        self.encrypt_menu_btn.setText("")
        self.encrypt_menu_btn.setIcon(icon7)
        self.encrypt_menu_btn.setIconSize(QtCore.QSize(30, 30))
        self.encrypt_menu_btn.setCheckable(True)
        self.encrypt_menu_btn.setAutoExclusive(True)
        self.encrypt_menu_btn.setObjectName("encrypt_menu_btn")
        self.verticalLayout.addWidget(self.encrypt_menu_btn)
        self.decrypt_menu_btn = QtWidgets.QPushButton(self.icon_only_widget)
        self.decrypt_menu_btn.setText("")
        self.decrypt_menu_btn.setIcon(icon8)
        self.decrypt_menu_btn.setIconSize(QtCore.QSize(30, 30))
        self.decrypt_menu_btn.setCheckable(True)
        self.decrypt_menu_btn.setAutoExclusive(True)
        self.decrypt_menu_btn.setObjectName("decrypt_menu_btn")
        self.verticalLayout.addWidget(self.decrypt_menu_btn)
        self.key_menu_btn = QtWidgets.QPushButton(self.icon_only_widget)
        self.key_menu_btn.setText("")
        self.key_menu_btn.setIcon(icon9)
        self.key_menu_btn.setIconSize(QtCore.QSize(26, 26))
        self.key_menu_btn.setCheckable(True)
        self.key_menu_btn.setAutoExclusive(True)
        self.key_menu_btn.setObjectName("key_menu_btn")
        self.verticalLayout.addWidget(self.key_menu_btn)
        self.files_menu_btn = QtWidgets.QPushButton(self.icon_only_widget)
        self.files_menu_btn.setText("")
        self.files_menu_btn.setIcon(icon10)
        self.files_menu_btn.setIconSize(QtCore.QSize(26, 26))
        self.files_menu_btn.setCheckable(True)
        self.files_menu_btn.setAutoExclusive(True)
        self.files_menu_btn.setObjectName("files_menu_btn")
        self.verticalLayout.addWidget(self.files_menu_btn)
        self.settings_menu_btn = QtWidgets.QPushButton(self.icon_only_widget)
        self.settings_menu_btn.setText("")
        self.settings_menu_btn.setIcon(icon11)
        self.settings_menu_btn.setIconSize(QtCore.QSize(28, 28))
        self.settings_menu_btn.setCheckable(True)
        self.settings_menu_btn.setAutoExclusive(True)
        self.settings_menu_btn.setObjectName("settings_menu_btn")
        self.verticalLayout.addWidget(self.settings_menu_btn)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 202, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.exit_btn = QtWidgets.QPushButton(self.icon_only_widget)
        self.exit_btn.setStyleSheet("QPushButton:hover{\n"
"background-color: rgb(195, 7, 63);\n"
"border:none;\n"
"border-radius:4px;\n"
"}")
        self.exit_btn.setText("")
        self.exit_btn.setIcon(icon12)
        self.exit_btn.setObjectName("exit_btn")
        self.verticalLayout_3.addWidget(self.exit_btn)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(5)
        self.menu_btn.toggled['bool'].connect(self.icon_only_widget.setVisible) # type: ignore
        self.menu_btn.toggled['bool'].connect(self.full_menu_widget.setHidden) # type: ignore
        self.encrypt_menu_btn.toggled['bool'].connect(self.encrypt_menu_btn_2.setChecked) # type: ignore
        self.decrypt_menu_btn.toggled['bool'].connect(self.decrypt_menu_btn_2.setChecked) # type: ignore
        self.key_menu_btn.toggled['bool'].connect(self.key_menu_btn_2.setChecked) # type: ignore
        self.files_menu_btn.toggled['bool'].connect(self.files_menu_btn_2.setChecked) # type: ignore
        self.settings_menu_btn.toggled['bool'].connect(self.settings_menu_btn_2.setChecked) # type: ignore
        self.encrypt_menu_btn_2.toggled['bool'].connect(self.encrypt_menu_btn.setChecked) # type: ignore
        self.decrypt_menu_btn_2.toggled['bool'].connect(self.decrypt_menu_btn.setChecked) # type: ignore
        self.key_menu_btn_2.toggled['bool'].connect(self.key_menu_btn.setChecked) # type: ignore
        self.files_menu_btn_2.toggled['bool'].connect(self.files_menu_btn.setChecked) # type: ignore
        self.settings_menu_btn_2.toggled['bool'].connect(self.settings_menu_btn.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_input.setPlaceholderText(_translate("MainWindow", "Search..."))
        self.res_file_line.setPlaceholderText(_translate("MainWindow", "chosen file..."))
        self.choose_file_btn.setText(_translate("MainWindow", "Choose file..."))
        self.choose_folder_btn.setText(_translate("MainWindow", "Choose folder..."))
        self.info_btn.setText(_translate("MainWindow", "info"))
        self.label_protect.setText(_translate("MainWindow", "Protect"))
        self.choose_file_btn_2.setText(_translate("MainWindow", "Choose file..."))
        self.choose_folder_btn_2.setText(_translate("MainWindow", "Choose folder..."))
        self.label_unlock.setText(_translate("MainWindow", "Unlock"))
        self.label_secure_plus.setText(_translate("MainWindow", "Secure+"))
        self.res_file_line_3.setPlaceholderText(_translate("MainWindow", "chosen file..."))
        self.choose_file_btn_3.setText(_translate("MainWindow", "Choose file..."))
        self.info_btn_2.setText(_translate("MainWindow", "info"))
        self.choose_file_btn_4.setText(_translate("MainWindow", "Choose file..."))
        self.choose_folder_btn_4.setText(_translate("MainWindow", "Choose folder..."))
        self.label_filemanager.setText(_translate("MainWindow", "File eraser"))
        self.radioButton.setText(_translate("MainWindow", "English"))
        self.radioButton_2.setText(_translate("MainWindow", "Русский"))
        self.label_language.setText(_translate("MainWindow", "Language"))
        self.label_lisence.setText(_translate("MainWindow", "Lisence"))
        self.lisence_btn.setText(_translate("MainWindow", "read"))
        self.label_instructions.setText(_translate("MainWindow", "Instructions"))
        self.instruction_btn.setText(_translate("MainWindow", "learn"))
        self.label_gmail.setText(_translate("MainWindow", "dkardash7@gmail.com"))
        self.label_whitepart.setText(_translate("MainWindow", "Archer"))
        self.label_redpart.setText(_translate("MainWindow", "protect. version 1.3.1  Kardash D. all rights reserved"))
        self.label_2.setText(_translate("MainWindow", "Welcome back!"))
        self.label_username.setText(_translate("MainWindow", "Bionic"))
        self.label_3.setText(_translate("MainWindow", "With us since: "))
        self.label_regdate.setText(_translate("MainWindow", "09.05.2023"))
        self.label_4.setText(_translate("MainWindow", "You can find instructions for this app in settings menu"))
        self.label_5.setText(_translate("MainWindow", "Have a good day!"))
        self.delete_acc_btn.setText(_translate("MainWindow", "Delete account"))
        self.logo_label_2.setText(_translate("MainWindow", "Archer"))
        self.encrypt_menu_btn_2.setText(_translate("MainWindow", "Protect"))
        self.decrypt_menu_btn_2.setText(_translate("MainWindow", "Unlock"))
        self.key_menu_btn_2.setText(_translate("MainWindow", "Secure+"))
        self.files_menu_btn_2.setText(_translate("MainWindow", "Filecures"))
        self.settings_menu_btn_2.setText(_translate("MainWindow", "Settings"))
        self.exit_btn_2.setText(_translate("MainWindow", "Exit"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
